version: "3"
services:
  bootstrap:
    build: geth
    depends_on:
      - netstats
    env_file: .env
    entrypoint: /root/start.sh
    command: '--datadir=$DATA_DIR --nodekeyhex=$NODEKEY_HEX --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=$NETWORKID --rpc --rpcaddr="0.0.0.0 --port=$BOOTSTRAP_PORT"'
    volumes:
      - ./data/genesis.json:/root/files/genesis.json:ro
      - ./data/keystore:$DATA_DIR/keystore:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "$BOOTSTRAP_PORT:$BOOTSTRAP_PORT"
      - "$BOOTSTRAP_PORT:$BOOTSTRAP_PORT/udp"

  geth:
    build: geth
    depends_on:
      - bootstrap
    env_file: .env
    entrypoint: /root/start.sh
    volumes:
      - ./data/genesis.json:/root/files/genesis.json:ro
      - ./data/keystore:$DATA_DIR/keystore:rw
      - /etc/localtime:/etc/localtime:ro
    command: '--datadir=$DATA_DIR  --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=$NETWORKID --rpc --bootnodes="enode://$ENODE@$BOOTSTRAP_HOSTNAME:$BOOTSTRAP_PORT"'
    ports:
      - "8545:8545"

  gethminer:
    build: geth
    depends_on:
      - bootstrap
    env_file: .env
    entrypoint: /root/start.sh
    volumes:
      - ./data/genesis.json:/root/files/genesis.json:ro
      - ./data/keystore:$DATA_DIR/keystore:rw
      - /etc/localtime:/etc/localtime:ro
    command: '--datadir=$DATA_DIR --mine --minerthreads=1 --rpccorsdomain="*" --networkid=$NETWORKID --rpc --bootnodes="enode://$ENODE@$BOOTSTRAP_HOSTNAME:$BOOTSTRAP_PORT"'

  netstats:
    build: eth-netstats
    env_file: .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
