version: "3"

services:

  eth-netstats:
    build: eth-netstats/
    ports:
     - "3000:3000"
    env_file: .env
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - "./data:/data"

  geth:
    build: geth/
    links:
     - eth-bootstrap
     - eth-netstats
    env_file: .env
    entrypoint: /root/run.sh
    volumes:
      - ./data/genesis.json:/root/data/genesis.json:ro
      - ./data/keystore:/root/.ethereum/chain/keystore:rw
      - /etc/localtime:/etc/localtime:ro
    command: '--datadir=~/.ethereum/chain --rpccorsdomain="*" --networkid=$NETWORKID --rpc --bootnodes="enode://$ENODE@BOOTSTRAP:30303"'

  eth-bootstrap:
    build: geth/
    restart: on-failure
    hostname: bootstrap
    #links:
    #  - eth-netstats
    env_file: .env
    entrypoint: /root/run.sh
    command: '--datadir=~/.ethereum/chain --nodekeyhex=$NODEKEY_HEX --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=$NETWORKID --rpc --rpcaddr="0.0.0.0"'
    volumes:
      - ./data/genesis.json:/root/data/genesis.json:ro
      - ./data/keystore:/root/.ethereum/chain/keystore:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
